on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: 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
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
